### ISSUE TITLE
App isn't working

### ISSUE THREAD

**Issue by NathanBnm** [elfenware/badger#8]
I tried to launch the app again after last update but here it's how it's appearing, and it gets stuck like this:

![image](https://user-images.githubusercontent.com/45366162/54854051-f99a9e80-4cf1-11e9-9f66-30f7f32ea248.png)

**Comment by dar5hak** [comment]
Hmm… that's strange. Okay, can you help me debug this?

1. Kill the Badger process using something like Monitor or Optimizer.
2. Launch it from the command line using `com.github.elfenware.badger`.
3. What does the log say?

**Comment by dar5hak** [comment]
Okay, I have attempted a possible fix in 30e4e71. If you have some time, can you do this too?

1. Uninstall the AppCenter version if you have it.
2. Checkout the master branch and build it from there.
3. Log out and log back in.
4. Launch the app.

**Comment by NathanBnm** [comment]
I tried again and I had to open the app a few time before it stay open and not crash. This time it worked but I don't know why.

This is what I get in the Terminal:

```
nathan@Nathan:~$ com.github.elfenware.badger

💲️ Command line mode started
✔️ Activated
⚙️ State settings loaded

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:31.891: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:31.891: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:31.891: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:31.891: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:31.892: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:31.896: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:31.897: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:31.897: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:31.897: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:31.897: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:31.897: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:36.120: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:36.125: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:36.125: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:36.125: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:36.125: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:36.125: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:36.858: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:36.863: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:36.863: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:36.863: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:36.863: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:36.863: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:37.495: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:37.501: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:37.501: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:37.501: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:37.502: badger_reminder_toggle_timer: assertion 'self != NULL' failed

** (com.github.elfenware.badger:4266): CRITICAL **: 10:33:37.502: badger_reminder_toggle_timer: assertion 'self != NULL' failed
```
But the app is appearing now. Don't now why it wasn't before:

![image](https://user-images.githubusercontent.com/45366162/54864419-685e1300-4d57-11e9-81b0-5353b8e74492.png)

Actually the window is too large for it's content.

**Comment by NathanBnm** [comment]
Finally the application crashes after a few minutes with a segmentation error

**Comment by NathanBnm** [comment]
> Okay, I have attempted a possible fix in [30e4e71](https://github.com/elfenware/badger/commit/30e4e71466dc9a0b991df8d03faac933160e15e6). If you have some time, can you do this too?
> 
>     1. Uninstall the AppCenter version if you have it.
> 
>     2. Checkout the master branch and build it from there.
> 
>     3. Log out and log back in.
> 
>     4. Launch the app.

After this the app is starting correctly but I still have the CRITICAL messages in the Terminal

**Comment by NathanBnm** [comment]
App is still crashing after a while with a segmentation fault

**Comment by dar5hak** [comment]
Hmm… I see. Thanks for your findings. Let me see what I can do about the segfault and CRITICAL messages, but meanwhile I will at least push a patch version so that this fix is available to everyone.

As for the window size, you can resize it to your preference, then close the window manually. It should remember your preference the next time you open it.

**Comment by dar5hak** [comment]
@NathanBnm Did you see any notifications when you built it from source?

**Comment by NathanBnm** [comment]
> Hmm… I see. Thanks for your findings. Let me see what I can do about the segfault and CRITICAL messages, but meanwhile I will at least push a patch version so that this fix is available to everyone.

Great :+1: 

> As for the window size, you can resize it to your preference, then close the window manually. It should remember your preference the next time you open it.

I think you should directly make the window smaller at first app startup.

> @NathanBnm Did you see any reminders when you built it from source?

What do you mean?

**Comment by dar5hak** [comment]
> I think you should directly make the window smaller at first app startup.

[These](https://github.com/elfenware/badger/blob/master/data/gschema.xml#L36) are the defaults, but I guess it differs from screen to screen.

> What do you mean?

When you checked out master and ran it from there, did it actually show you the periodic reminders, like blinking your eyes?

**Comment by NathanBnm** [comment]
> ![image](https://user-images.githubusercontent.com/45366162/54854051-f99a9e80-4cf1-11e9-9f66-30f7f32ea248.png)

Actually I still have this on first startup like before.

And on second startup, when I quit and relaunch the app I have this:

![image](https://user-images.githubusercontent.com/45366162/54879502-eabf0380-4e39-11e9-9508-4d23cab74473.png)

If I resize the app it remembers the windows size now. But it's still too large at first startup.

I still have the CRITICAL, I don't see any reminder for now. I'll tell you if there are after building from source.

**Comment by NathanBnm** [comment]
I noticed that the "Reminders" label isn't translated anymore too

**Comment by dar5hak** [comment]
Those CRITICAL messages and the segfault are coming from C and I have no idea where they map to in the Vala code. I'll need to do some blind experiments.

**Comment by NathanBnm** [comment]
Okay, Reminders are working :clap:

**Comment by dar5hak** [comment]
Good to know!

**Comment by NathanBnm** [comment]
This is fixed now! :+1:

**Comment by NathanBnm** [comment]
Actually there is still the CRITICAL error, but it's working anyway

**Comment by dar5hak** [comment]
Those have actually been around since before the blank window bug appeared, and haven't caused any noticeable harm, so I'm keeping them on a low priority for now.
